"use client";
import "./globals.css";
import Header from './header';
import { darkTheme } from "./theme/themes";
import { ThemeProvider, CssBaseline } from "@mui/material";
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <body>
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
